name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Check Firebase CLI Version
        run: firebase --version

      - name: Write Firebase Service Account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      - name: Deploy to Firebase Hosting
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" > $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
          npm install -g firebase-tools
          firebase deploy --only hosting --project trendawy-flutter

